spring.config.import=optional:file:.env[.properties]

spring.application.name=life-os-backend

server.port=${PORT:8080}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:604800000}

# Gmail SMTP
sendgrid.api.key=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

sendgrid.sender.email=haripragateesh7@gmail.com
sendgrid.sender.name=Life OS