package com.lifeos.entity;

import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.UUID;

@Entity
@Table(name = "tasks")
public class Task {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false)
    private String taskName;

    @Column(length = 500)
    private String description;

    @Column(nullable = false)
    private LocalDate taskDate;

    @Column(nullable = false)
    private LocalTime taskTime;

    @Column(nullable = false)
    private String priority;

    @Column(nullable = false)
    private Boolean completed = false;

    // =====================================================
    // Recurrence Fields
    // =====================================================

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private RepeatType repeatType = RepeatType.NEVER;

    /**
     * Whether recurrence is currently active.
     * If false, no future occurrences will be generated.
     */
    @Column(nullable = false)
    private Boolean recurrenceActive = true;

    /**
     * True only for the master recurring task.
     * Generated occurrences are always false.
     */
    @Column(nullable = false)
    private Boolean recurrenceMaster = false;

    /**
     * Points to the master recurring task.
     *
     * Master Task:
     * masterTaskId = null
     *
     * Generated Occurrence:
     * masterTaskId = master's UUID
     */
    @Column
    private UUID masterTaskId;

    /**
     * Tracks the latest occurrence generated by the scheduler.
     * Used to prevent duplicate occurrence generation.
     *
     * Only used for master recurring tasks.
     */
    @Column
    private LocalDate lastGeneratedDate;

    // =====================================================

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    public Task() {
    }

    @PrePersist
    protected void onCreate() {

        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }

        if (completed == null) {
            completed = false;
        }

        if (priority == null || priority.isBlank()) {
            priority = "MEDIUM";
        }

        if (repeatType == null) {
            repeatType = RepeatType.NEVER;
        }

        if (recurrenceActive == null) {
            recurrenceActive = true;
        }

        if (recurrenceMaster == null) {
            recurrenceMaster = false;
        }
    }

    // =====================================================
    // Getters and Setters
    // =====================================================

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getTaskDate() {
        return taskDate;
    }

    public void setTaskDate(LocalDate taskDate) {
        this.taskDate = taskDate;
    }

    public LocalTime getTaskTime() {
        return taskTime;
    }

    public void setTaskTime(LocalTime taskTime) {
        this.taskTime = taskTime;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public Boolean getCompleted() {
        return completed;
    }

    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    public RepeatType getRepeatType() {
        return repeatType;
    }

    public void setRepeatType(RepeatType repeatType) {
        this.repeatType = repeatType;
    }

    public Boolean getRecurrenceActive() {
        return recurrenceActive;
    }

    public void setRecurrenceActive(Boolean recurrenceActive) {
        this.recurrenceActive = recurrenceActive;
    }

    public Boolean getRecurrenceMaster() {
        return recurrenceMaster;
    }

    public void setRecurrenceMaster(Boolean recurrenceMaster) {
        this.recurrenceMaster = recurrenceMaster;
    }

    public UUID getMasterTaskId() {
        return masterTaskId;
    }

    public void setMasterTaskId(UUID masterTaskId) {
        this.masterTaskId = masterTaskId;
    }

    public LocalDate getLastGeneratedDate() {
        return lastGeneratedDate;
    }

    public void setLastGeneratedDate(LocalDate lastGeneratedDate) {
        this.lastGeneratedDate = lastGeneratedDate;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}